Confluent 5 (#2)
* upgrading to v5

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -27,12 +27,13 @@ if [[ -z "${CONFLUENT_VERSION}" ]]; then
     exit 1
 fi
 
-ARCHIVE_URL=${ARCHIVE_URL_OVERRIDE:-http://packages.confluent.io/archive/4.0/confluent-oss-${CONFLUENT_VERSION}-2.11.tar.gz}
-wget -qO - $ARCHIVE_URL | tar -zxf -
-if ! [ $? ]; then
-    echo "FAILED to obtain confluent distribution" | indent
-    exit 1
-fi
+# Uncomment this code block if you want to download the archive from the internet
+#ARCHIVE_URL=${ARCHIVE_URL_OVERRIDE:-http://packages.confluent.io/archive/5.2/confluent-${CONFLUENT_VERSION}-2.12.tar.gz}
+#wget -qO - $ARCHIVE_URL | tar -zxf -
+#if ! [ $? ]; then
+#    echo "FAILED to obtain confluent distribution" | indent
+#    exit 1
+#fi
 
 cp -a confluent-${CONFLUENT_VERSION}/* $BUILD_DIR/
 
@@ -58,6 +59,8 @@ trap "bin/${CONFLUENT_COMPONENT}-stop" SIGINT SIGTERM
 
 bin/${CONFLUENT_COMPONENT}-start confluent.properties
 EOF
+
+cat ${BUILD_DIR}/bin/run-confluent
 
 chmod a+x ${BUILD_DIR}/bin/run-confluent
 
